name: auto_update_rule
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream
        run: |
          git config --global user.name 'halfteas'
          git config --global user.email 'halfteas@outlook.com'
          git clone https://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@github.com/halfteas/Rule_Script.git temp
          cd temp 
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git
          git pull --rebase upstream master
          git push origin master         
