name: Sync Repository A to Repository B

on:
  schedule:
    - cron: '0 7 * * *' # 每天 0 点触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository B
      uses: actions/checkout@v2
      with:
        repository: halfteas/Rule_Script
        ref: master # 仓库 B 的主分支名字
        token: ${{ secrets.GITHUB_TOKEN }} # 添加 token 权限以允许 push
        

      
    - name: Commit and push changes
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git 
        git pull --rebase upstream master 
        git push origin master
       