name: auto_update_rule
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream
        run: |
          git clone https://github.com/blackmatrix7/ios_rule_script.git temp
          cd temp 
          git remote add upstream https://github.com/halfteas/Rule_Script.git
          git pull origin master
          git push upstream master         
