name: auto_update_rule
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream
        run: |
          
          git clone https://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@github.com/halfteas/Rule_Script.git temp
          cd temp 
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git
          git pull --rebase upstream master
          git push origin master         
