name: Sync Repository A to Repository B

on:
  schedule:
    - cron: '50 4 * * *' # 每天 0 点触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository A
      uses: actions/checkout@v2
      with:
        repository: blackmatrix7/ios_rule_script
        ref: master # 仓库 A 的主分支名字
        
    - name: Checkout Repository B
      uses: actions/checkout@v2
      with:
        repository: halfteas/Rule_Script
        ref: master # 仓库 B 的主分支名字
        token: ${{ secrets.GITHUB_TOKEN }} # 添加 token 权限以允许 push
        
    - name: Copy files from Repository A to Repository B
      run: cp -r $GITHUB_WORKSPACE/ios_rule_script/* $GITHUB_WORKSPACE/Rule_Script/
      
    - name: Commit and push changes
      run: |
        cd $GITHUB_WORKSPACE/Rule_Script/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Sync changes from Repository A"
        git push