name: Sync Repo

on:
  schedule:
    - cron:  '50 6 * * *' # 每天凌晨运行

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: 'current_repo'

    - name: Add source repo as a remote
      run: |
        cd current_repo
        git remote add source https://github.com/blackmatrix7/ios_rule_script.git

    - name: Fetch source repo changes
      run: |
        cd current_repo
        git fetch source

    - name: Merge or rebase source repo changes
      run: |
        cd current_repo
        git merge source/master --allow-unrelated-histories -m "Merge changes from source repo" || \
        git rebase source/master -m "Rebase changes from source repo"

    - name: Push changes
      run: |
        cd current_repo
        git config --global user.email "halfteas@outlook.com"
        git config --global user.name "halfteas"
        git push

       
