name: Sync Repo

on:
  schedule:
    - cron:  '50 1 * * *' # 每天凌晨运行

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: 'blackmatrix7/ios_rule_script'
        token: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的token
        path: 'ios_rule_script'

    - name: Copy files to the current repo
      run: |
        cp -r ios_rule_script/* ./
        rm -rf ios_rule_script

    - name: Commit changes
      run: |
        git config --global user.email "GithubAction@example.com"
        git config --global user.name "GithubAction"
        git add .
        git commit -m 'Update from blackmatrix7/ios_rule_script' -a || echo "No changes to commit"
        git push

