name: Sync Repo A to Repo B

on:
  schedule:
    - cron: '0 14 * * *'  # 每天午夜执行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: 'halfteas/Rule_Script'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Repo changes from Repo A
        run: |
          git config --global user.email "halfteas@outlook.com"
          git config --global user.name "halfteas"
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git
          git pull --rebase upstream master
          git pull --rebase origin master
          git push origin master
