

name: Sync Repo A to Repo B

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 0 点触发，可以根据需要调整时间
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: halfteas/Rule_Script # 替换为你的仓库 B
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Repo A
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add repoA https://github.com/blackmatrix7/ios_rule_script.git
          git fetch repoA
          git merge repoA/master --allow-unrelated-histories -m "sync: merge changes from repoA"
          git push origin master


          
